language: python

python:
  - "2.7"
  - "3.6"

before_install:
  - openssl aes-256-cbc -K $encrypted_c7fcc23724b8_key -iv $encrypted_c7fcc23724b8_iv -in deploy.enc -out deploy -d

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python test_travis.py

before_deploy:
  - chmod 600 deploy && mv deploy ~/.ssh/id_rsa
  - curl -O https://raw.githubusercontent.com/EGC-G2-Trabajo-1718/integracion/master/tools/deploy.sh

deploy:
  - provider: heroku
    api_key:
      secure: 2dc00a9f-b59c-43fb-b241-5a7b3897417c 
    app: visualizacion
    on: dev-visualizacion
  - provider: script
    skip_cleanup: true
    script: ssh -o StrictHostKeyChecking=no deploy@egc.duckdns.org 'bash -s' < deploy.sh portal-votaciones
    on:
      branch: master
      python: "3.6"
